export type CheckCode = {
    id: string,
    phoneNumber: string,
    createTime: string,
    updateTime: string,
    verifyingId: string,
}
export type RegisterInfo = {
    id: string,
    userNo: string,
    hasCerted: boolean,
    life: number,
    nikeName: string,
    openid: string,
    sex: string,
    province: string,
    city: string,
    country: string,
    headimgurl: string,
    unionid: string,
    privilege: string[],
    language: string,
    description: string,
}
export type Article = {
    id:string,
    createTime:string,
    title:string,
    ownerId:string,
    articleType:number,
    resource:string[],
    categories:string[],
    paymentStatus:string,
    bucketName:string,
    published:boolean,
    likeNum:number,
    readNum:number,
    hasCollection:boolean,
    income:number,
    profitIncome:number,
    avatorUrl:string,
    nikeName:string,
    userNo:string,
    cost:number,
    isLike:boolean,
    collectionTime:string,
    paymentTime:string,
    groupId:string,
    modular:string,
    ligicalDel:number,
    updateTime:string,
    simpleUrl:string,
    videoUrl:string,
    certified:string,
}